/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe (unauthenticated, in-VNet only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the current user's identity, role, and group membership */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            oid: string;
                            displayName: string;
                            /** @enum {string} */
                            role: "user" | "admin";
                            groups?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's conversations (most-recent first) */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    continuationToken?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["ConversationSummary"][];
                            continuationToken?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a new (empty) conversation; returns its id */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Conversation"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get full conversation (including turns + citations) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Conversation"];
                    };
                };
                /** @description Not found or not owned by caller */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Soft-delete the conversation. All associated user-uploaded documents
         *     and AI Search passages are purged within 1 hour (SC-012).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted; deletion in progress */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a chat message and stream the assistant's grounded answer
         * @description Server-Sent Events stream. Events:
         *       - `delta` — incremental token chunks
         *       - `citations` — citation list once retrieval completes
         *       - `done` — final usage + turnId + updatedConversation
         *       - `error` — terminal error
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatRequest"];
                };
            };
            responses: {
                /** @description SSE stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a document to be grounded against in the current conversation only
         * @description Multipart upload. The document is scoped to the caller's identity AND
         *     the parent conversation. It is NEVER added to the shared corpus and
         *     is purged when the conversation is deleted or expires.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        conversationId: string;
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Accepted; ingestion in progress */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentMeta"];
                    };
                };
                /** @description Document too large or per-conversation cap exceeded */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unsupported media type */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/citations/{documentId}": {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path: {
                documentId: string;
            };
            cookie?: never;
        };
        /**
         * Stream the source document for a citation, in-context
         * @description Returns the original document. The API enforces that the caller can
         *     only retrieve documents in scope `shared` or `user:<callerOid>`.
         *     For PDFs, the response is the PDF binary; the UI navigates to the
         *     cited page via `?page=N`. Image documents are returned as image bytes.
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                };
                header?: never;
                path: {
                    documentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Document binary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": unknown;
                        "application/pdf": unknown;
                        "image/png": unknown;
                        "image/jpeg": unknown;
                    };
                };
                /** @description Document not found or out of scope */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operational dashboard stats (admin only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminStats"];
                    };
                };
                /** @description Caller is not in the admin group */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent ingestion runs (admin only) */
        get: {
            parameters: {
                query?: {
                    scope?: "shared" | "user";
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is not in the admin group */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force a full re-ingestion of the shared corpus (admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted; run started */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is not in the admin group */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        ConversationSummary: {
            id: string;
            title: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Citation: {
            passageId: string;
            documentId: string;
            /**
             * @description "shared" = admin-curated corpus.
             *     "user" = the caller's own uploaded document. Cross-user citations
             *     cannot occur (enforced server-side; see SC-011).
             * @enum {string}
             */
            scope: "shared" | "user";
            page: number;
            snippet?: string;
            /** Format: float */
            score?: number;
        };
        Turn: {
            turnId: string;
            /** @enum {string} */
            role: "user" | "assistant";
            content: string;
            citations?: components["schemas"]["Citation"][];
            /** Format: date-time */
            createdAt: string;
        };
        Conversation: {
            id: string;
            title: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            turns: components["schemas"]["Turn"][];
            uploadedDocumentIds?: string[];
        };
        DocumentMeta: {
            id: string;
            /** @enum {string} */
            scope: "shared" | "user";
            fileName: string;
            mimeType: string;
            sizeBytes: number;
            ingestion: {
                /** @enum {string} */
                status: "queued" | "cracking" | "indexing" | "indexed" | "failed" | "skipped";
                /** Format: date-time */
                startedAt?: string | null;
                /** Format: date-time */
                completedAt?: string | null;
                passageCount?: number | null;
                errorReason?: string | null;
                errorCode?: string | null;
            };
        };
        ChatRequest: {
            /** @description Existing or freshly-created conversation id. */
            conversationId: string;
            message: string;
            /**
             * @description When true, retrieval considers the caller's uploaded documents in
             *     this conversation in addition to the shared corpus.
             * @default true
             */
            useUploads: boolean;
        };
        AdminStats: {
            sharedDocuments?: number;
            sharedPassages?: number;
            totalConversations?: number;
            totalUsers?: number;
            chatRequests24h?: number;
            /** Format: float */
            declineRate7d?: number;
            lastIngestionRun?: {
                id?: string;
                status?: string;
                /** Format: date-time */
                startedAt?: string;
                /** Format: date-time */
                completedAt?: string | null;
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
